apiVersion : apps/v1
kind: Deployment
metadata:
  name: microservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice 
    spec:
      containers:
        - name: microservice 
          image: aksdevopsacr45.azurecr.io/microservice
          ports:
          - containerPort: 80